/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    noticias: Noticia;
    documentos: Documento;
    proyectos: Proyecto;
    miembros: Miembro;
    downloads: Download;
    'video-views': VideoView;
    eventos: Evento;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    documentos: DocumentosSelect<false> | DocumentosSelect<true>;
    proyectos: ProyectosSelect<false> | ProyectosSelect<true>;
    miembros: MiembrosSelect<false> | MiembrosSelect<true>;
    downloads: DownloadsSelect<false> | DownloadsSelect<true>;
    'video-views': VideoViewsSelect<false> | VideoViewsSelect<true>;
    eventos: EventosSelect<false> | EventosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'sitio-general': SitioGeneral;
    contacto: Contacto;
    'pagina-inicio': PaginaInicio;
    'pagina-quienes-somos': PaginaQuienesSomo;
    'pagina-gobernanza': PaginaGobernanza;
    'pagina-h2v': PaginaH2V;
    'pagina-sectores': PaginaSectore;
    'pagina-hoja-ruta': PaginaHojaRuta;
    'pagina-comunidad': PaginaComunidad;
    'pagina-capital-humano': PaginaCapitalHumano;
    'pagina-marco-regulatorio': PaginaMarcoRegulatorio;
    'pagina-transparencia': PaginaTransparencia;
    'pagina-mediateca': PaginaMediateca;
    'pagina-proyectos': PaginaProyecto;
    'pagina-privacidad': PaginaPrivacidad;
    'pagina-accesibilidad': PaginaAccesibilidad;
    'guia-admin': GuiaAdmin;
  };
  globalsSelect: {
    'sitio-general': SitioGeneralSelect<false> | SitioGeneralSelect<true>;
    contacto: ContactoSelect<false> | ContactoSelect<true>;
    'pagina-inicio': PaginaInicioSelect<false> | PaginaInicioSelect<true>;
    'pagina-quienes-somos': PaginaQuienesSomosSelect<false> | PaginaQuienesSomosSelect<true>;
    'pagina-gobernanza': PaginaGobernanzaSelect<false> | PaginaGobernanzaSelect<true>;
    'pagina-h2v': PaginaH2VSelect<false> | PaginaH2VSelect<true>;
    'pagina-sectores': PaginaSectoresSelect<false> | PaginaSectoresSelect<true>;
    'pagina-hoja-ruta': PaginaHojaRutaSelect<false> | PaginaHojaRutaSelect<true>;
    'pagina-comunidad': PaginaComunidadSelect<false> | PaginaComunidadSelect<true>;
    'pagina-capital-humano': PaginaCapitalHumanoSelect<false> | PaginaCapitalHumanoSelect<true>;
    'pagina-marco-regulatorio': PaginaMarcoRegulatorioSelect<false> | PaginaMarcoRegulatorioSelect<true>;
    'pagina-transparencia': PaginaTransparenciaSelect<false> | PaginaTransparenciaSelect<true>;
    'pagina-mediateca': PaginaMediatecaSelect<false> | PaginaMediatecaSelect<true>;
    'pagina-proyectos': PaginaProyectosSelect<false> | PaginaProyectosSelect<true>;
    'pagina-privacidad': PaginaPrivacidadSelect<false> | PaginaPrivacidadSelect<true>;
    'pagina-accesibilidad': PaginaAccesibilidadSelect<false> | PaginaAccesibilidadSelect<true>;
    'guia-admin': GuiaAdminSelect<false> | GuiaAdminSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Usuarios de la plataforma. Administradores y editores gestionan contenido; los registrados solo pueden descargar documentos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nombre: string;
  /**
   * Administrador: acceso total. Editor: puede crear y editar noticias, documentos, eventos. Registrado: solo puede descargar documentos. (El primer usuario del sitio siempre se crea como Administrador.)
   */
  role: 'admin' | 'editor' | 'registrado';
  /**
   * Organización a la que pertenece el usuario.
   */
  institucion?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Sube imágenes (JPG, PNG, WebP) y documentos (PDF, Word). Estos archivos se usan en noticias, documentos y otras secciones del sitio. NO subas archivos de texto plano (.txt) — solo imágenes y PDFs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe brevemente el contenido. Ej: "Logo CORFO", "Foto reunión marzo 2026".
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Publica noticias sobre seminarios, talleres, reuniones de gobernanza, acuerdos y avances del programa. Las noticias aparecen en la sección "Noticias" y en la página de inicio. Usa "Publicar" para que la noticia sea visible; "Guardar borrador" la deja solo aquí en el admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  /**
   * Título principal que verán los visitantes. Sé claro y descriptivo.
   */
  titulo: string;
  /**
   * Identificador único para la URL. Usa solo letras minúsculas, números y guiones. Ej: "lanzamiento-programa-h2v"
   */
  slug: string;
  /**
   * Resumen de 1-2 oraciones que aparece en el listado de noticias. Máximo 300 caracteres.
   */
  extracto: string;
  /**
   * El texto completo de la noticia. Puedes agregar párrafos, negritas, listas, enlaces e imágenes.
   */
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Imagen principal de la noticia. Sube una imagen JPG o PNG (recomendado: 1200x630 px).
   */
  imagen: number | Media;
  /**
   * Fecha que se mostrará en la noticia.
   */
  fecha: string;
  /**
   * Categoría para filtrar la noticia.
   */
  categoria?: ('seminario' | 'taller' | 'gobernanza' | 'acuerdo' | 'proyecto' | 'general') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Sube documentos técnicos, de difusión, regulatorios o de capacitación. Aparecen en la sección "Recursos y Documentación" del sitio. Los visitantes registrados pueden descargarlos y cada descarga queda registrada.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos".
 */
export interface Documento {
  id: number;
  /**
   * Nombre descriptivo del documento. Ej: "Estrategia Nacional de Hidrógeno Verde"
   */
  titulo: string;
  /**
   * Breve descripción del contenido del documento (2-3 oraciones).
   */
  descripcion: string;
  /**
   * Sube el archivo PDF o Word que los visitantes podrán descargar.
   */
  archivo: number | Media;
  /**
   * Imagen que se mostrará como miniatura del documento. Si no subes una, se usará un icono genérico.
   */
  thumbnail?: (number | null) | Media;
  /**
   * Categoría del documento. Los visitantes pueden filtrar por tipo.
   */
  tipo: 'tecnico' | 'difusion' | 'regulatorio' | 'capacitacion';
  /**
   * Año del documento. Los visitantes pueden filtrar por año.
   */
  anio: number;
  /**
   * Contador automático de descargas. No lo modifiques manualmente.
   */
  descargas?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Agrega proyectos de hidrógeno verde que aparecerán en el Mapa de Proyectos. Cada proyecto se muestra como un marcador en el mapa con su información.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos".
 */
export interface Proyecto {
  id: number;
  /**
   * Ej: "Planta piloto H2V Temuco", "Proyecto eólico Araucanía Norte"
   */
  nombre: string;
  /**
   * Descripción breve del proyecto (2-4 oraciones). Aparece en el popup del mapa.
   */
  descripcion: string;
  /**
   * Nombre de la empresa u organización responsable del proyecto.
   */
  empresa: string;
  /**
   * En qué etapa se encuentra el proyecto actualmente.
   */
  etapa: 'planificacion' | 'pilotaje' | 'desarrollo' | 'operacion';
  /**
   * Si es un proyecto en La Araucanía o en otra región de Chile.
   */
  region: 'araucania' | 'nacional';
  /**
   * Latitud y longitud para ubicar el proyecto en el mapa. Puedes obtenerlas desde Google Maps haciendo clic derecho en la ubicación.
   */
  coordenadas: {
    /**
     * Ej: -38.7359 (Temuco)
     */
    lat: number;
    /**
     * Ej: -72.5904 (Temuco)
     */
    lng: number;
  };
  /**
   * Capacidad instalada en megawatts (si aplica).
   */
  capacidadMW?: number | null;
  /**
   * Producción estimada en toneladas por año (si aplica).
   */
  produccionTonAnio?: number | null;
  /**
   * Foto o render del proyecto.
   */
  imagen?: (number | null) | Media;
  /**
   * URL al sitio web del proyecto o empresa, si existe.
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestiona los integrantes del Consejo de Dirección, Comité Consultivo y Unidad de Coordinación. Aparecen en las páginas "Quiénes Somos" y "Gobernanza".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "miembros".
 */
export interface Miembro {
  id: number;
  /**
   * Nombre y apellido de la persona.
   */
  nombre: string;
  /**
   * Ej: "Presidente", "Director", "Consejero", "Coordinador Programa"
   */
  cargo: string;
  /**
   * Organización que representa. Ej: "Ministerio de Energía", "CODESSER", "Universidad de Talca"
   */
  institucion: string;
  /**
   * A qué instancia de la gobernanza pertenece esta persona.
   */
  instancia: 'consejo' | 'comite' | 'unidad';
  /**
   * Foto de perfil. Recomendado: formato cuadrado, mínimo 200x200 px.
   */
  foto?: (number | null) | Media;
  /**
   * Descripción breve de cómo contribuye al programa. Ej: "Vinculación con el sector y orientación estratégica"
   */
  aporte?: string | null;
  suplente?: string | null;
  /**
   * Número para ordenar. Menor número aparece primero. Ej: 1, 2, 3...
   */
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro automático de descargas de documentos. Esta tabla se llena sola — no necesitas crear entradas manualmente. Úsala para ver quién descargó qué documento y cuándo (indicadores CORFO).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads".
 */
export interface Download {
  id: number;
  /**
   * El documento que fue descargado.
   */
  documento: number | Documento;
  /**
   * Usuario registrado que realizó la descarga (si estaba logueado).
   */
  user?: (number | null) | User;
  downloadedAt: string;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro automático de reproducción de videos. Esta tabla se llena sola — no crees entradas a mano. Sirve para el indicador CORFO de visualizaciones: cada "play" es una visualización y cada "fin" trae los segundos vistos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-views".
 */
export interface VideoView {
  id: number;
  /**
   * Título del video reproducido.
   */
  videoTitulo: string;
  /**
   * Proveedor e ID del video (ej. youtube:abc123).
   */
  videoKey: string;
  evento: 'play' | 'fin';
  /**
   * Segundos efectivamente reproducidos en la sesión (relevante en el evento "fin").
   */
  segundosVistos?: number | null;
  /**
   * Identificador de la sesión de reproducción (agrupa play y fin).
   */
  sessionId?: string | null;
  /**
   * Usuario registrado que reprodujo el video (si estaba logueado).
   */
  user?: (number | null) | User;
  watchedAt: string;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Publica eventos del programa: seminarios, talleres, ferias, reuniones y capacitaciones. Aparecen en la sección "Eventos" del sitio. Usa "Publicar" para que el evento sea visible.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos".
 */
export interface Evento {
  id: number;
  /**
   * Ej: "Seminario Internacional de Hidrógeno Verde", "Taller de capacitación para sector forestal"
   */
  titulo: string;
  /**
   * Detalle del evento: programa, expositores, objetivos, público objetivo.
   */
  descripcion: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Día en que comienza el evento.
   */
  fecha: string;
  /**
   * Solo si el evento dura más de un día.
   */
  fechaFin?: string | null;
  /**
   * Ej: "Hotel Dreams, Temuco", "Online vía Zoom", "Universidad de La Frontera, Temuco"
   */
  lugar: string;
  tipo?: ('seminario' | 'taller' | 'feria' | 'reunion' | 'capacitacion' | 'otro') | null;
  /**
   * Imagen promocional del evento.
   */
  imagen?: (number | null) | Media;
  /**
   * URL al formulario de inscripción. Ej: enlace a Google Forms o Eventbrite.
   */
  urlInscripcion?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'documentos';
        value: number | Documento;
      } | null)
    | ({
        relationTo: 'proyectos';
        value: number | Proyecto;
      } | null)
    | ({
        relationTo: 'miembros';
        value: number | Miembro;
      } | null)
    | ({
        relationTo: 'downloads';
        value: number | Download;
      } | null)
    | ({
        relationTo: 'video-views';
        value: number | VideoView;
      } | null)
    | ({
        relationTo: 'eventos';
        value: number | Evento;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nombre?: T;
  role?: T;
  institucion?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  extracto?: T;
  contenido?: T;
  imagen?: T;
  fecha?: T;
  categoria?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos_select".
 */
export interface DocumentosSelect<T extends boolean = true> {
  titulo?: T;
  descripcion?: T;
  archivo?: T;
  thumbnail?: T;
  tipo?: T;
  anio?: T;
  descargas?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos_select".
 */
export interface ProyectosSelect<T extends boolean = true> {
  nombre?: T;
  descripcion?: T;
  empresa?: T;
  etapa?: T;
  region?: T;
  coordenadas?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  capacidadMW?: T;
  produccionTonAnio?: T;
  imagen?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "miembros_select".
 */
export interface MiembrosSelect<T extends boolean = true> {
  nombre?: T;
  cargo?: T;
  institucion?: T;
  instancia?: T;
  foto?: T;
  aporte?: T;
  suplente?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads_select".
 */
export interface DownloadsSelect<T extends boolean = true> {
  documento?: T;
  user?: T;
  downloadedAt?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-views_select".
 */
export interface VideoViewsSelect<T extends boolean = true> {
  videoTitulo?: T;
  videoKey?: T;
  evento?: T;
  segundosVistos?: T;
  sessionId?: T;
  user?: T;
  watchedAt?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos_select".
 */
export interface EventosSelect<T extends boolean = true> {
  titulo?: T;
  descripcion?: T;
  fecha?: T;
  fechaFin?: T;
  lugar?: T;
  tipo?: T;
  imagen?: T;
  urlInscripcion?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Nombre del sitio, texto SEO, texto del footer y logos institucionales. Estos valores se usan en toda la plataforma.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sitio-general".
 */
export interface SitioGeneral {
  id: number;
  /**
   * Nombre que aparece en la pestaña del navegador y en resultados de búsqueda.
   */
  nombreSitio?: string | null;
  /**
   * Texto que aparece en Google debajo del nombre del sitio. Máximo 200 caracteres.
   */
  descripcionSEO?: string | null;
  /**
   * Texto que aparece al pie de todas las páginas del sitio.
   */
  footerTexto?: string | null;
  /**
   * Segunda línea del footer. Ej: "Programa Desarrollo Productivo Sostenible — CORFO"
   */
  footerPrograma?: string | null;
  /**
   * Logos que aparecen en el footer y la página de inicio. Sube los logos de CORFO, CODESSER, UTalca, etc.
   */
  instituciones?:
    | {
        nombre: string;
        logo: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Datos de contacto que aparecen en la página de Contacto y en el footer del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacto".
 */
export interface Contacto {
  id: number;
  /**
   * Email público al que llegarán los mensajes del formulario de contacto.
   */
  email: string;
  /**
   * Dirección o ciudad que se muestra en la página de contacto.
   */
  ubicacion?: string | null;
  /**
   * Número de teléfono público. Déjalo vacío si no aplica.
   */
  telefono?: string | null;
  /**
   * Nombre completo del ejecutor principal del Bien Público.
   */
  ejecutor1?: string | null;
  /**
   * Nombre del co-ejecutor técnico.
   */
  ejecutor2?: string | null;
  /**
   * Institución mandante del programa.
   */
  mandante?: string | null;
  /**
   * Código CORFO del Bien Público.
   */
  codigoBP?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contenido del hero, botones y tarjetas de acceso rápido de la página principal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-inicio".
 */
export interface PaginaInicio {
  id: number;
  hero: {
    /**
     * Título grande que aparece sobre el banner principal.
     */
    titulo: string;
    /**
     * Texto debajo del título. Máximo 250 caracteres.
     */
    subtitulo: string;
    /**
     * Texto del botón principal. Ej: "Conozca el Programa"
     */
    ctaPrimario?: string | null;
    /**
     * Texto del botón secundario. Ej: "Ver Proyectos en el Mapa"
     */
    ctaSecundario?: string | null;
  };
  seccionExplora?: {
    /**
     * Título de la sección de tarjetas de acceso rápido.
     */
    titulo?: string | null;
    /**
     * Tarjetas que aparecen debajo del hero. Cada una lleva a una sección del sitio.
     */
    cards?:
      | {
          /**
           * Ej: "Mapa de Proyectos", "Noticias"
           */
          titulo: string;
          /**
           * Breve descripción de la sección (1 oración).
           */
          descripcion: string;
          /**
           * Ruta de la sección. Ej: "/proyectos", "/noticias"
           */
          enlace: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Descripción del Bien Público, instituciones participantes y títulos de las secciones de Consejo y Comité.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-quienes-somos".
 */
export interface PaginaQuienesSomo {
  id: number;
  hero?: {
    /**
     * Título del banner.
     */
    titulo?: string | null;
    /**
     * Texto debajo del título.
     */
    subtitulo?: string | null;
  };
  /**
   * Descripción del BP 24BP-269085: objetivo, alcance, instituciones.
   */
  bienPublico: {
    titulo?: string | null;
    /**
     * Texto libre sobre el Bien Público. Puedes usar negritas, listas y enlaces.
     */
    contenido: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  /**
   * Instituciones que participan en el programa (CORFO, CODESSER, UTalca, etc.).
   */
  instituciones?:
    | {
        /**
         * Nombre de la institución.
         */
        nombre: string;
        /**
         * Rol en el programa. Ej: "Ejecutor principal", "Co-ejecutor técnico"
         */
        rol: string;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Título que aparece sobre la lista de miembros del Consejo.
   */
  consejoTitulo?: string | null;
  consejoDescripcion?: string | null;
  /**
   * Título que aparece sobre la lista de miembros del Comité.
   */
  comiteTitulo?: string | null;
  comiteDescripcion?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Modelo de gobernanza: niveles estratégico y operativo, funciones y periodicidad.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-gobernanza".
 */
export interface PaginaGobernanza {
  id: number;
  hero?: {
    /**
     * Título del banner.
     */
    titulo?: string | null;
    /**
     * Texto debajo del título.
     */
    subtitulo?: string | null;
  };
  /**
   * Párrafo introductorio sobre el modelo de gobernanza.
   */
  descripcion?: string | null;
  /**
   * Consejo de Dirección — instancia máxima de decisión.
   */
  nivelEstrategico?: {
    titulo?: string | null;
    descripcion?: string | null;
    funciones?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Frecuencia y modalidad de reuniones.
     */
    periodicidad?: string | null;
  };
  /**
   * Unidad de Coordinación y Gestión — ejecución del programa.
   */
  nivelOperativo?: {
    titulo?: string | null;
    descripcion?: string | null;
    funciones?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Frecuencia y modalidad de reuniones.
     */
    periodicidad?: string | null;
  };
  /**
   * Textos de las cajas del diagrama. Si cambia la estructura de gobernanza, actualízalos aquí y el dibujo se adapta solo.
   */
  diagrama?: {
    /**
     * Caja superior (nivel estratégico).
     */
    consejo?: string | null;
    /**
     * Caja lateral conectada al Consejo.
     */
    comite?: string | null;
    /**
     * Caja central (nivel operativo).
     */
    unidad?: string | null;
    /**
     * Los equipos que dependen de la Unidad. Se reparten automáticamente en el diagrama (máximo 6). Si no agregas ninguno, se muestran los 4 estándar.
     */
    equipos?:
      | {
          nombre: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Fotos de actividades del programa (reuniones, talleres, terreno). Mientras no subas ninguna, la página muestra espacios "Foto próximamente". Ideal: fotos horizontales.
   */
  actividades?:
    | {
        foto: number | Media;
        /**
         * Se muestra bajo la foto. Ej: "Taller con sector forestal, mayo 2026".
         */
        titulo?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contenido educativo: qué es el H2V, electrólisis, tipos de electrolizadores, cadena de valor y derivados.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-h2v".
 */
export interface PaginaH2V {
  id: number;
  hero?: {
    /**
     * Título del banner.
     */
    titulo?: string | null;
    /**
     * Texto debajo del título del banner.
     */
    subtitulo?: string | null;
  };
  /**
   * Sección introductoria sobre qué es el hidrógeno verde.
   */
  queEs?: {
    titulo?: string | null;
    /**
     * Texto libre explicando qué es el H2V. Puedes usar negritas, listas y enlaces.
     */
    contenido?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Pasos del proceso de electrólisis mostrados como tarjetas numeradas.
   */
  electrolisis?: {
    titulo?: string | null;
    pasos?:
      | {
          /**
           * Ej: "Fuente renovable", "Electrolizador"
           */
          titulo: string;
          descripcion: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Tipos de electrolizadores (PEM, Alcalino, SOEC, etc.) con sus características.
   */
  electrolizadores?:
    | {
        nombre: string;
        descripcion: string;
        /**
         * Ej: "Comercial", "En desarrollo"
         */
        madurez?: string | null;
        /**
         * Ej: "$800-1500/kW"
         */
        costo?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Etapas de la cadena de valor del H2V: producción, almacenamiento, transporte, uso.
   */
  cadenaValor?:
    | {
        titulo: string;
        descripcion: string;
        /**
         * Un emoji representativo. Ej: "⚡", "🔋"
         */
        icono?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Productos derivados del hidrógeno verde: amoníaco, metanol, e-combustibles, etc.
   */
  derivados?:
    | {
        nombre: string;
        descripcion: string;
        /**
         * Ej: "Fertilizantes verdes", "Transporte marítimo"
         */
        aplicacion?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tarjetas de enlace al final de la página. Si no agregas ninguna, se muestran las 4 estándar (Sectores, Capital Humano, Hoja de Ruta, Marco Regulatorio).
   */
  exploraMas?:
    | {
        titulo: string;
        descripcion: string;
        /**
         * Se elige de la lista para evitar enlaces rotos.
         */
        enlace:
          | '/hidrogeno-verde/sectores'
          | '/hidrogeno-verde/capital-humano'
          | '/hidrogeno-verde/hoja-de-ruta'
          | '/hidrogeno-verde/marco-regulatorio'
          | '/proyectos'
          | '/recursos/documentos'
          | '/noticias'
          | '/contacto';
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Sectores productivos regionales con potencial de integración del H2V (forestal, agro, transporte, etc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-sectores".
 */
export interface PaginaSectore {
  id: number;
  hero?: {
    /**
     * Título del banner.
     */
    titulo?: string | null;
    /**
     * Texto debajo del título.
     */
    subtitulo?: string | null;
  };
  /**
   * Cada sector se muestra como una tarjeta con descripción y lista de oportunidades.
   */
  sectores?:
    | {
        /**
         * Ej: "Forestal y Biomasa", "Agroindustrial"
         */
        nombre: string;
        /**
         * Un emoji representativo. Ej: "🌲", "🚛"
         */
        icono?: string | null;
        descripcion: string;
        oportunidades?:
          | {
              texto: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Timeline de hitos estratégicos del programa H2V Araucanía (2024-2050).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-hoja-ruta".
 */
export interface PaginaHojaRuta {
  id: number;
  hero?: {
    /**
     * Título del banner.
     */
    titulo?: string | null;
    /**
     * Texto debajo del título.
     */
    subtitulo?: string | null;
  };
  /**
   * Cada hito se muestra como un punto en la línea de tiempo de la página.
   */
  hitos?:
    | {
        /**
         * Ej: "2024-2026", "2030", "2050"
         */
        periodo: string;
        titulo: string;
        descripcion: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Texto que aparece al final de la página.
   */
  notaFinal?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Participación ciudadana, compromiso territorial y glosario Mapudungún.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-comunidad".
 */
export interface PaginaComunidad {
  id: number;
  hero?: {
    /**
     * Título del banner.
     */
    titulo?: string | null;
    /**
     * Texto debajo del título.
     */
    subtitulo?: string | null;
  };
  /**
   * Párrafo introductorio sobre la participación comunitaria.
   */
  introduccion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Mecanismos de participación ciudadana en la gobernanza del programa.
   */
  participacion?: {
    titulo?: string | null;
    items?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Compromisos del programa con las comunidades y el territorio.
   */
  compromisos?: {
    titulo?: string | null;
    items?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Términos de energía en Mapudungún con su traducción al español. Ej: "Küme Newen" → "Buena energía"
   */
  glosario?:
    | {
        mapudungun: string;
        espanol: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Perfiles laborales emergentes y programas de formación del BP para la industria H2V.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-capital-humano".
 */
export interface PaginaCapitalHumano {
  id: number;
  hero?: {
    /**
     * Título del banner.
     */
    titulo?: string | null;
    /**
     * Texto debajo del título.
     */
    subtitulo?: string | null;
  };
  /**
   * Párrafo introductorio sobre capital humano y formación.
   */
  introduccion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Nuevos perfiles laborales que surgen con la industria del H2V.
   */
  perfiles?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Programas de capacitación que ofrece o gestionará el Bien Público.
   */
  programas?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Texto sobre la oportunidad que representa el H2V para la fuerza laboral regional.
   */
  notaOportunidad?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Normativa y políticas nacionales relevantes para el desarrollo del H2V en Chile.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-marco-regulatorio".
 */
export interface PaginaMarcoRegulatorio {
  id: number;
  hero?: {
    /**
     * Título del banner.
     */
    titulo?: string | null;
    /**
     * Texto debajo del título.
     */
    subtitulo?: string | null;
  };
  /**
   * Leyes, estrategias y planes relevantes. Cada uno se muestra como una tarjeta.
   */
  documentos?:
    | {
        /**
         * Nombre completo de la ley o documento. Ej: "Ley 21.305 de Eficiencia Energética"
         */
        titulo: string;
        descripcion: string;
        /**
         * Cómo se aplica este documento al contexto regional.
         */
        relevancia?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Rendición de cuentas: actas, registro de actividades, uso de recursos e indicadores de avance.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-transparencia".
 */
export interface PaginaTransparencia {
  id: number;
  hero?: {
    /**
     * Título del banner.
     */
    titulo?: string | null;
    /**
     * Texto debajo del título.
     */
    subtitulo?: string | null;
  };
  /**
   * Párrafo introductorio que aparece bajo el encabezado.
   */
  introduccion?: string | null;
  /**
   * Cada bloque tiene título, descripción y estado. Cuando publiques un documento, cambia su estado (ej. de "Próximamente" a "Disponible").
   */
  items?:
    | {
        titulo: string;
        descripcion: string;
        /**
         * Ej: Próximamente, Disponible, En proceso.
         */
        estado?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Videos, infografías y material multimedia. Agrega recursos o deja el mensaje de "próximamente" mientras no haya material.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-mediateca".
 */
export interface PaginaMediateca {
  id: number;
  hero?: {
    /**
     * Título del banner.
     */
    titulo?: string | null;
    /**
     * Texto debajo del título.
     */
    subtitulo?: string | null;
  };
  /**
   * Cada recurso: título, tipo, enlace y descripción. Si dejas esta lista vacía, se muestra el mensaje de "próximamente".
   */
  recursos?:
    | {
        titulo: string;
        tipo?: ('video' | 'infografia' | 'presentacion' | 'documento') | null;
        /**
         * Enlace al video (YouTube/Vimeo) o al archivo.
         */
        url: string;
        descripcion?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Se muestra mientras la lista de recursos esté vacía.
   */
  mensajeVacio?: {
    titulo?: string | null;
    subtitulo?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Encabezado de la página del Mapa de Proyectos. Los proyectos que aparecen en el mapa se gestionan en Contenido → Proyectos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-proyectos".
 */
export interface PaginaProyecto {
  id: number;
  hero?: {
    /**
     * Título del banner.
     */
    titulo?: string | null;
    /**
     * Texto debajo del título.
     */
    subtitulo?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Página legal de Política de Privacidad. El email de contacto que muestra la página se toma de Configuración → Contacto (no hay que tocarlo aquí).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-privacidad".
 */
export interface PaginaPrivacidad {
  id: number;
  hero?: {
    /**
     * Título del banner.
     */
    titulo?: string | null;
    /**
     * Texto debajo del título.
     */
    subtitulo?: string | null;
  };
  /**
   * Se muestra al inicio de la política. Actualízala cada vez que cambies el texto. Ej: "julio 2026".
   */
  fechaActualizacion?: string | null;
  /**
   * Si escribes aquí, este texto REEMPLAZA completo al texto estándar de la página. Si lo dejas vacío, se muestra el texto estándar del programa.
   */
  contenido?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Página de Declaración de Accesibilidad. El email de contacto que muestra la página se toma de Configuración → Contacto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-accesibilidad".
 */
export interface PaginaAccesibilidad {
  id: number;
  hero?: {
    /**
     * Título del banner.
     */
    titulo?: string | null;
    /**
     * Texto debajo del título.
     */
    subtitulo?: string | null;
  };
  /**
   * Si escribes aquí, este texto REEMPLAZA completo al texto estándar de la página. Si lo dejas vacío, se muestra el texto estándar del programa.
   */
  contenido?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Guía paso a paso para administrar el sitio H2V Araucanía: publicar noticias, subir documentos, editar las páginas, gestionar usuarios y resolver problemas comunes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guia-admin".
 */
export interface GuiaAdmin {
  id: number;
  /**
   * Esta sección contiene la guía de uso del panel de administración. No necesitas modificarla.
   */
  instrucciones?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   *
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * CÓMO ESTÁ ORGANIZADO ESTE PANEL
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * El menú lateral tiene 4 grupos:
   * • CONTENIDO: lo que publicas seguido (Noticias, Documentos, Proyectos, Miembros, Eventos)
   * • PÁGINAS: los textos de cada página del sitio (Inicio, Quiénes Somos, Gobernanza, etc.)
   * • CONFIGURACIÓN: datos institucionales (solo administradores)
   * • SISTEMA / CUENTAS: archivos subidos y usuarios
   *
   * Regla de oro: todo campo tiene debajo una explicación breve. Léela antes de llenar.
   *
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 🔵 PASO 1: PUBLICAR UNA NOTICIA
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 1. En el menú lateral, haz clic en "Noticias"
   * 2. Haz clic en el botón "Crear nueva"
   * 3. Completa los campos:
   *    • Título: El titular de la noticia
   *    • URL amigable (slug): letras minúsculas y guiones. Ej: "lanzamiento-programa-h2v"
   *    • Resumen breve: 1-2 oraciones (máx 300 caracteres)
   *    • Contenido completo: El texto de la noticia. Puedes usar negritas, listas, enlaces
   *    • Imagen de portada: Haz clic y sube una imagen JPG o PNG
   *    • Fecha: Selecciona la fecha de la noticia
   *    • Categoría: Elige una (Seminario, Taller, Gobernanza, etc.)
   * 4. ✅ IMPORTANTE — para que la noticia SE VEA en el sitio, presiona el botón azul
   *    "Publicar cambios". Si presionas "Guardar borrador", la noticia queda guardada
   *    SOLO aquí en el admin (útil para terminarla otro día), pero NO aparece en el sitio.
   * 5. ¿Te equivocaste? Abre la noticia → pestaña "Versiones" → elige una versión anterior
   *    → "Restaurar". Cada guardado deja una copia.
   *
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 🔵 PASO 2: SUBIR UN DOCUMENTO
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 1. En el menú lateral, haz clic en "Documentos"
   * 2. Haz clic en "Crear nuevo"
   * 3. Completa:
   *    • Título del documento
   *    • Descripción: 2-3 oraciones sobre el contenido
   *    • Archivo: Sube el PDF o Word
   *    • Tipo: Técnico, Difusión, Regulatorio o Capacitación
   *    • Año: El año del documento
   * 4. Guardar
   * Los visitantes registrados podrán descargarlo. Cada descarga queda registrada automáticamente
   * (el contador "descargas" se llena solo: no lo modifiques).
   *
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 🔵 PASO 3: AGREGAR UN PROYECTO AL MAPA
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 1. En el menú lateral, haz clic en "Proyectos"
   * 2. Haz clic en "Crear nuevo"
   * 3. Completa:
   *    • Nombre del proyecto
   *    • Descripción breve
   *    • Empresa responsable
   *    • Etapa: Planificación, Pilotaje, Desarrollo u Operación
   *    • Ubicación: Araucanía o Nacional
   *    • Coordenadas: Ve a Google Maps, haz clic derecho en la ubicación,
   *      copia la latitud y longitud. Ej: Temuco = Lat -38.7359, Lng -72.5904
   *    • Capacidad y producción (si los conoces)
   * 4. Guardar
   * El proyecto aparecerá como un punto en el mapa interactivo.
   * (El título de la página del mapa se edita en Páginas → Mapa de Proyectos.)
   *
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 🔵 PASO 4: AGREGAR MIEMBROS DE GOBERNANZA
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 1. En el menú lateral, haz clic en "Miembros de Gobernanza"
   * 2. Haz clic en "Crear nuevo"
   * 3. Completa:
   *    • Nombre completo
   *    • Cargo: Ej: "Director", "Consejero", "Coordinador"
   *    • Institución: Ej: "Ministerio de Energía", "CODESSER"
   *    • Instancia: Elige a cuál pertenece:
   *      - Consejo de Dirección (nivel estratégico)
   *      - Comité Consultivo Técnico Científico
   *      - Unidad de Coordinación y Gestión (nivel operativo)
   *    • Foto (opcional): Sube una foto cuadrada
   *    • Orden: Número para ordenar (1 aparece primero)
   * 4. Guardar
   * Aparecerá automáticamente en "Quiénes Somos" y "Gobernanza".
   *
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 🔵 PASO 5: CREAR UN EVENTO
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 1. En el menú lateral, haz clic en "Eventos"
   * 2. Haz clic en "Crear nuevo"
   * 3. Completa:
   *    • Nombre del evento
   *    • Descripción detallada
   *    • Fecha de inicio (y de término si dura varios días)
   *    • Lugar: dirección física o "Online vía Zoom"
   *    • Tipo: Seminario, Taller, Feria, etc.
   *    • Enlace de inscripción (opcional): URL a formulario de registro
   * 4. ✅ Presiona "Publicar cambios" para que el evento sea visible
   *    ("Guardar borrador" lo deja solo en el admin).
   *
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 🔵 PASO 6: SUBIR FOTOS DE ACTIVIDADES (página Gobernanza)
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 1. Menú lateral → grupo Páginas → "Gobernanza"
   * 2. Baja hasta "Evidencia de Actividades (galería de fotos)"
   * 3. "Añadir fila" → sube la foto (ideal horizontal) → escribe una descripción breve
   *    Ej: "Taller con sector forestal, mayo 2026"
   * 4. Guardar
   * Mientras no subas fotos, la página muestra "Foto próximamente".
   * En la misma página puedes editar los textos del diagrama "Estructura del Modelo".
   *
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 🟢 EDITAR TEXTOS DE LAS PÁGINAS
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * En el menú lateral, bajo el grupo "Páginas", encontrarás una entrada por página del sitio:
   * • Página de Inicio: título, subtítulo y tarjetas de la portada
   * • Quiénes Somos: descripción del Bien Público, instituciones
   * • Gobernanza: niveles, funciones, diagrama y galería de fotos
   * • Hidrógeno Verde: contenido educativo, electrolizadores, derivados y tarjetas "Explora más"
   * • Sectores Productivos: sectores y oportunidades
   * • Hoja de Ruta: hitos del timeline
   * • Comunidad: participación, glosario Mapudungún
   * • Capital Humano: perfiles y programas
   * • Marco Regulatorio: documentos normativos
   * • Transparencia: ítems de transparencia
   * • Mediateca: recursos audiovisuales
   * • Mapa de Proyectos: título y subtítulo de la página del mapa
   * • Política de Privacidad: fecha de actualización y texto legal
   * • Accesibilidad: texto de la declaración
   * En todas: lo que dejes vacío usa el texto estándar del sitio; lo que escribas lo reemplaza.
   *
   * En "Configuración" (solo administradores):
   * • Configuración General: nombre del sitio, texto del footer, logos de instituciones participantes
   * • Contacto: email público, ubicación, ejecutores, mandante y código del Bien Público.
   *   El email que se cambia aquí se actualiza AUTOMÁTICAMENTE en Contacto, el footer,
   *   Privacidad y Accesibilidad.
   * Nota: el bloque "Proyecto apoyado por" (CORFO) del sitio es fijo: lo exige el manual de
   * comunicaciones de Corfo y no se puede quitar desde el panel.
   *
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 🟡 USUARIOS Y ROLES
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * • Administrador: puede todo (incluido borrar contenido, gestionar usuarios y configuración).
   * • Editor: puede crear y editar contenido, pero NO puede borrar, NO ve "Usuarios"
   *   y NO puede tocar la Configuración. Es el rol adecuado para delegar publicaciones.
   * • Registrado: solo descarga documentos desde el sitio público; no entra a este panel.
   * Para crear un editor: Usuarios → Crear nuevo → rol "Editor" (solo un administrador puede).
   *
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 🔴 PROBLEMAS COMUNES Y CÓMO SALIR
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * • "Escribí una noticia y no aparece en el sitio" → seguramente quedó como BORRADOR.
   *   Ábrela y presiona "Publicar cambios".
   * • "Me equivoqué al editar" → pestaña "Versiones" del documento → "Restaurar".
   * • "Borré algo sin querer" → el borrado ES PERMANENTE (por eso solo los administradores
   *   pueden borrar). Si era importante, se puede recuperar desde el respaldo de la base de
   *   datos: contacta al soporte técnico.
   * • "Puse mal la clave varias veces y no puedo entrar" → por seguridad la cuenta se bloquea
   *   tras 5 intentos. ESPERA 10 MINUTOS y vuelve a intentar. Si olvidaste la clave, usa
   *   "¿Olvidaste tu contraseña?" en la pantalla de entrada.
   * • "Subí una imagen y no se ve" → verifica que sea JPG, PNG o WebP (no .txt ni .zip).
   * • Los cambios publicados se ven en el sitio en segundos: recarga la página del sitio.
   *   Si no aparecen, revisa que hayas presionado "Publicar cambios" y no "Guardar borrador".
   *
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * 📎 SOBRE LOS ARCHIVOS (fotos y PDFs)
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   * • Imágenes: JPG, PNG o WebP. Documentos: PDF o Word.
   * • Los archivos se guardan en un almacenamiento en la nube y quedan disponibles
   *   de forma permanente.
   * • Antes de subir, ponles un nombre claro (ej: "seminario-temuco-2026.pdf").
   *
   * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   *
   */
  guiaCompleta?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sitio-general_select".
 */
export interface SitioGeneralSelect<T extends boolean = true> {
  nombreSitio?: T;
  descripcionSEO?: T;
  footerTexto?: T;
  footerPrograma?: T;
  instituciones?:
    | T
    | {
        nombre?: T;
        logo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacto_select".
 */
export interface ContactoSelect<T extends boolean = true> {
  email?: T;
  ubicacion?: T;
  telefono?: T;
  ejecutor1?: T;
  ejecutor2?: T;
  mandante?: T;
  codigoBP?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-inicio_select".
 */
export interface PaginaInicioSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
        ctaPrimario?: T;
        ctaSecundario?: T;
      };
  seccionExplora?:
    | T
    | {
        titulo?: T;
        cards?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              enlace?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-quienes-somos_select".
 */
export interface PaginaQuienesSomosSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  bienPublico?:
    | T
    | {
        titulo?: T;
        contenido?: T;
      };
  instituciones?:
    | T
    | {
        nombre?: T;
        rol?: T;
        logo?: T;
        id?: T;
      };
  consejoTitulo?: T;
  consejoDescripcion?: T;
  comiteTitulo?: T;
  comiteDescripcion?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-gobernanza_select".
 */
export interface PaginaGobernanzaSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  descripcion?: T;
  nivelEstrategico?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        funciones?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        periodicidad?: T;
      };
  nivelOperativo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        funciones?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        periodicidad?: T;
      };
  diagrama?:
    | T
    | {
        consejo?: T;
        comite?: T;
        unidad?: T;
        equipos?:
          | T
          | {
              nombre?: T;
              id?: T;
            };
      };
  actividades?:
    | T
    | {
        foto?: T;
        titulo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-h2v_select".
 */
export interface PaginaH2VSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  queEs?:
    | T
    | {
        titulo?: T;
        contenido?: T;
      };
  electrolisis?:
    | T
    | {
        titulo?: T;
        pasos?:
          | T
          | {
              titulo?: T;
              descripcion?: T;
              id?: T;
            };
      };
  electrolizadores?:
    | T
    | {
        nombre?: T;
        descripcion?: T;
        madurez?: T;
        costo?: T;
        id?: T;
      };
  cadenaValor?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        icono?: T;
        id?: T;
      };
  derivados?:
    | T
    | {
        nombre?: T;
        descripcion?: T;
        aplicacion?: T;
        id?: T;
      };
  exploraMas?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        enlace?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-sectores_select".
 */
export interface PaginaSectoresSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  sectores?:
    | T
    | {
        nombre?: T;
        icono?: T;
        descripcion?: T;
        oportunidades?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-hoja-ruta_select".
 */
export interface PaginaHojaRutaSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  hitos?:
    | T
    | {
        periodo?: T;
        titulo?: T;
        descripcion?: T;
        id?: T;
      };
  notaFinal?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-comunidad_select".
 */
export interface PaginaComunidadSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  introduccion?: T;
  participacion?:
    | T
    | {
        titulo?: T;
        items?:
          | T
          | {
              texto?: T;
              id?: T;
            };
      };
  compromisos?:
    | T
    | {
        titulo?: T;
        items?:
          | T
          | {
              texto?: T;
              id?: T;
            };
      };
  glosario?:
    | T
    | {
        mapudungun?: T;
        espanol?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-capital-humano_select".
 */
export interface PaginaCapitalHumanoSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  introduccion?: T;
  perfiles?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  programas?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  notaOportunidad?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-marco-regulatorio_select".
 */
export interface PaginaMarcoRegulatorioSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  documentos?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        relevancia?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-transparencia_select".
 */
export interface PaginaTransparenciaSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  introduccion?: T;
  items?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        estado?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-mediateca_select".
 */
export interface PaginaMediatecaSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  recursos?:
    | T
    | {
        titulo?: T;
        tipo?: T;
        url?: T;
        descripcion?: T;
        id?: T;
      };
  mensajeVacio?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-proyectos_select".
 */
export interface PaginaProyectosSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-privacidad_select".
 */
export interface PaginaPrivacidadSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  fechaActualizacion?: T;
  contenido?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-accesibilidad_select".
 */
export interface PaginaAccesibilidadSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titulo?: T;
        subtitulo?: T;
      };
  contenido?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guia-admin_select".
 */
export interface GuiaAdminSelect<T extends boolean = true> {
  instrucciones?: T;
  guiaCompleta?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}